
export const SET_USERNAME_LOGIN = "SET_USERNAME_LOGIN"
export const SET_PASSWORD_LOGIN = "SET_PASSWORD_LOGIN"

export const SET_PASSWORD_REGISTER = "SET_PASSWORD_REGISTER"
export const SET_USERNAME_REGISTER = "SET_USERNAME_REGISTER"


